// Error Codes
module.exports = {
  ERR_BAD_REQUEST: 400,
  ERR_UNAUTHORIZED: 401,
  ERR_FORBIDDEN: 403,
  ERR_NOT_FOUND: 404,
  ERR_METHOD_NOT_ALLOWED: 405,
  ERR_NOT_ACCEPTABLE: 406,
  ERR_CONFLICT: 409,
  ERR_LENGTH_REQUIRED: 411,
  ERR_PRECONDITION_FAILED: 412,
  ERR_PAYLOAD_TOO_LARGE: 413,
  ERR_INTERNAL_SERVER_ERROR: 500,
};
